spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/muha
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
   #email sender
  mail:
    host: smtp.gmail.com
    port: 25
    username: mailfromspringboot0@gmail.com
    password: okm9ijnuhb
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 5656
  error:
    include-message: always

# jwt token
application:
  jwt:
    secretKey: java4isthebestgroup
    tokenPrefix: Bearer
    expirationDateAfterDays: 30

